apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "text-processor-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "text-processor-helm.name" . }}
    helm.sh/chart: {{ include "text-processor-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "text-processor-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "text-processor-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4567
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /document
          #     port: 4567
          # readinessProbe:
          #   httpGet:
          #     path: /document
          #     port: 4567
          command: ["java"]
          args: ["-jar", "text-processor-1.0-SNAPSHOT-all.jar", "-t", "{{ .Values.arguments.tika }}", "-db", "{{ .Values.arguments.db }}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
